repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: https://github.com/pylint-dev/pylint
    rev: v2.17.4
    hooks:
      - id: pylint

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        args: [--disable-error-code, attr-defined, --disable-error-code, union-attr]
